//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int PRODUCT_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public decimal PRODUCT_PRICE { get; set; }
        public string PRODUCT_PICTURE_ADDRESS { get; set; }
        public Nullable<long> PRODUCTS_QUANTITY { get; set; }
        public string PRODUCTS_COUNTRY { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
